#This workflow should print “hello how are you” when a new change is pushed to main branch

name: Exercise 1
on:
    push:
        branches:
            - main
jobs:
  learning-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: "print message"
        run: "echo hello how are you"
      - name: list environmental variables
        run: printenv             

#When the user pushes changes to main branch, show all the environmental variables in output
        